const pairing = {
  pairing_no: 'T5012',
  date_range: '2021-01-01 to 2021-01-07',
  crew_complement: { P: 2, FA: 5, GJ: 1, GY: 1, BL: 2, JP: 2, MD: 1 },
  check_in: '07:20',
  check_out: '19:15',
  sequence: [
    {
      index: 1,
      type: 'flight',
      flight_no: '1',
      dept_stn: 'YYZ',
      arrival_stn: 'HND',
      dept_time: '13:15',
      arrival_time: '15:40',
      flight_credit: '13:25',
      duty: '14:55',
      days_operating: '1234567',
      equipment: '789',
      onboard_meals: ['HB', 'HD', 'SS'],
    },
    {
      index: 2,
      type: 'layover',
      layover_stn: 'HND',
      hotel: 'The Westin Tokyo HND DT',
      layover_start: '15:55',
      layover_end: '17:40',
      layover_expenses: 'DSBLD',
      layover_cico: 1,
      layover_expenses_total: '127.89',
      layover_length: '24:45',
    },
    {
      index: 3,
      type: 'flight',
      flight_no: '2',
      dept_stn: 'HND',
      arrival_stn: 'YYZ',
      dept_time: '17:40',
      arrival_time: '17:10',
      flight_credit: '12:30',
      duty: '13:45',
      days_operating: '1234567',
      equipment: '789',
      onboard_meals: ['HB', 'HD', 'SS'],
    },
  ],
  block_time: '25:55',
  duty_guarantee: '0:00',
  duty_time: '28:40',
  total_allowance: '219.80',
  time_away: '53:25',
  total_block: '25:55',
};

export default pairing;
